security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        login:
#          pattern:      ^/login$
#          security:     false

        secured_area:
            pattern:                  /.*
            provider:                 in_memory
            form_login:
                check_path:           /loginCheck
                login_path:           /login
                default_target_path:  /portal_homepage
            logout:
                path:                 /logout
                target:               /
            security:                 true
            anonymous:                true
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"

    access_control:
        - { path: /login,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user,      roles: ROLE_USER }
#        - { path: /.*,        roles: IS_AUTHENTICATED_ANONYMOUSLY }

