default:
  pattern:  /
  defaults: { _controller: PortalBundle:Home:home }

portal_homepage:
    pattern:  /user
    defaults: { _controller: PortalBundle:Home:home }

patient_search:
    pattern:  /patient/search
    defaults: { _controller: PortalBundle:Patient/PatientSearch:index }

portal_login:
    pattern: /login
    defaults: { _controller: PortalBundle:Security:login }

portal_login_check:
    pattern: /loginCheck

portal_logout:
    pattern: /logout



