default:
  pattern:  /
  defaults: { _controller: PortalBundle:Home:home }

portal_homepage:
    pattern:  /user
    defaults: { _controller: PortalBundle:Home:home }

patient_search:
    pattern:  /patient/search
    defaults: { _controller: PortalBundle:Patient/PatientSearch:index }

patient_dashboard:
    pattern:  /patient/dashboard/{id}
    defaults: { _controller: PortalBundle:Patient/PatientDashboard:index }

patient_register:
    pattern: /patient/register/{id}
    defaults: {_controller: PortalBundle:Patient/PatientRegister:index }

patient_register_save:
    pattern: /patient/register/save/{id}
    defaults: {_controller: PortalBundle:Patient/PatientRegister:save }

patient_chart:
    pattern:  /patient/chart/{id}
    defaults: { _controller: PortalBundle:Patient/PatientCommon:getChart }

patient_review:
    pattern: /patient/encounter/review/{reviewType}/{treatmentType}/{patientId}
    defaults: { _controller: PortalBundle:Patient/PatientEncounter:review }

patient_call:
    pattern: /patient/encounter/call/{callType}/{treatmentType}/{patientId}
    defaults: { _controller: PortalBundle:Patient/PatientEncounter:telephoneCall }

patient_admission:
    pattern: /patient/admission/{admissionType}/{patientId}
    defaults: { _controller: PortalBundle:Patient/PatientAdmission:admission }

patient_create:
    pattern: /patient/create
    defaults: { _controller: PortalBundle:Patient/PatientCreate:createNewPatient }

portal_login:
    pattern: /login
    defaults: { _controller: PortalBundle:Security:login }

portal_login_check:
    pattern: /loginCheck

portal_logout:
    pattern: /logout



